nodes:
  - nodeId: node-0
    coordinates:
      x: 11.61
      'y': 38.38
    action: navigate
    eventType: navigation
  - nodeId: node-1
    coordinates:
      x: 45.8
      'y': 87.19
    action: navigate
    eventType: navigation
  - nodeId: node-2
    coordinates:
      x: 84.8
      'y': 43.91
    action: navigate
    eventType: navigation
  - nodeId: node-3
    coordinates:
      x: 0.65
      'y': 85.98
    action: navigate
    eventType: navigation
  - nodeId: node-4
    coordinates:
      x: 34.55
      'y': 26.83
    action: navigate
    eventType: navigation
  - nodeId: node-5
    coordinates:
      x: 77.81
      'y': 70.99
    action: navigate
    eventType: navigation
  - nodeId: node-6
    coordinates:
      x: 28.08
      'y': 8.05
    action: navigate
    eventType: navigation
  - nodeId: node-7
    coordinates:
      x: 61.43
      'y': 56.1
    action: navigate
    eventType: navigation
  - nodeId: node-8
    coordinates:
      x: 62.87
      'y': 77.01
    action: navigate
    eventType: navigation
  - nodeId: node-9
    coordinates:
      x: 57.38
      'y': 21.58
    action: navigate
    eventType: navigation
  - nodeId: node-10
    coordinates:
      x: 26.9
      'y': 60.51
    action: navigate
    eventType: navigation
  - nodeId: node-11
    coordinates:
      x: 28.66
      'y': 47.03
    action: navigate
    eventType: navigation
  - nodeId: node-12
    coordinates:
      x: 58.68
      'y': 69.8
    action: navigate
    eventType: navigation
  - nodeId: node-13
    coordinates:
      x: 2.41
      'y': 25.35
    action: navigate
    eventType: navigation
  - nodeId: node-14
    coordinates:
      x: 72.91
      'y': 12.21
    action: navigate
    eventType: navigation
  - nodeId: node-15
    coordinates:
      x: 80.76
      'y': 57.51
    action: navigate
    eventType: navigation
  - nodeId: node-16
    coordinates:
      x: 41.86
      'y': 63.08
    action: navigate
    eventType: navigation
  - nodeId: node-17
    coordinates:
      x: 97.64
      'y': 35.45
    action: navigate
    eventType: navigation
  - nodeId: node-18
    coordinates:
      x: 12.2
      'y': 32.52
    action: navigate
    eventType: navigation
  - nodeId: node-19
    coordinates:
      x: 6.82
      'y': 65.45
    action: navigate
    eventType: navigation
  - nodeId: node-20
    coordinates:
      x: 84.85
      'y': 10.48
    action: navigate
    eventType: navigation
edges:
  - source: node-0
    target: ../images/favicon.ico
    action: navigate
  - source: node-1
    target: ../styles/style.css
    action: navigate
  - source: node-2
    target: ../styles/dark.css
    action: navigate
  - source: node-3
    target: ../
    action: navigate
  - source: node-4
    target: '#info'
    action: navigate
  - source: node-5
    target: '#source'
    action: navigate
  - source: node-6
    target: '#bio'
    action: navigate
  - source: node-7
    target: '#email'
    action: navigate
  - source: node-8
    target: '#image'
    action: navigate
  - source: node-9
    target: '#password'
    action: navigate
  - source: node-10
    target: '#username'
    action: navigate
  - source: node-11
    target: Unknown
    action: navigate
  - source: node-12
    target: '#bio'
    action: navigate
  - source: node-13
    target: Unknown
    action: navigate
  - source: node-14
    target: '#email'
    action: navigate
  - source: node-15
    target: Unknown
    action: navigate
  - source: node-16
    target: '#image'
    action: navigate
  - source: node-17
    target: Unknown
    action: navigate
  - source: node-18
    target: '#password'
    action: navigate
  - source: node-19
    target: Unknown
    action: navigate
  - source: node-20
    target: '#username'
    action: navigate
