nodes:
  - nodeId: node-0
    coordinates:
      x: 90.98
      'y': 87.08
    action: navigate
    eventType: navigation
  - nodeId: node-1
    coordinates:
      x: 87.42
      'y': 27.61
    action: navigate
    eventType: navigation
  - nodeId: node-2
    coordinates:
      x: 6.41
      'y': 64.23
    action: navigate
    eventType: navigation
  - nodeId: node-3
    coordinates:
      x: 63
      'y': 95.4
    action: navigate
    eventType: navigation
  - nodeId: node-4
    coordinates:
      x: 81.11
      'y': 81.47
    action: navigate
    eventType: navigation
  - nodeId: node-5
    coordinates:
      x: 66.12
      'y': 60.27
    action: navigate
    eventType: navigation
  - nodeId: node-6
    coordinates:
      x: 56.33
      'y': 75.72
    action: navigate
    eventType: navigation
  - nodeId: node-7
    coordinates:
      x: 87.94
      'y': 34.43
    action: navigate
    eventType: navigation
  - nodeId: node-8
    coordinates:
      x: 97.49
      'y': 73.04
    action: navigate
    eventType: navigation
  - nodeId: node-9
    coordinates:
      x: 48.84
      'y': 53.74
    action: navigate
    eventType: navigation
  - nodeId: node-10
    coordinates:
      x: 1.85
      'y': 0.53
    action: navigate
    eventType: navigation
  - nodeId: node-11
    coordinates:
      x: 24.81
      'y': 1.71
    action: navigate
    eventType: navigation
  - nodeId: node-12
    coordinates:
      x: 66.64
      'y': 20.86
    action: navigate
    eventType: navigation
  - nodeId: node-13
    coordinates:
      x: 64.49
      'y': 30.33
    action: navigate
    eventType: navigation
  - nodeId: node-14
    coordinates:
      x: 46.57
      'y': 80.62
    action: navigate
    eventType: navigation
  - nodeId: node-15
    coordinates:
      x: 34.2
      'y': 61.94
    action: navigate
    eventType: navigation
  - nodeId: node-16
    coordinates:
      x: 58.88
      'y': 3.44
    action: navigate
    eventType: navigation
  - nodeId: node-17
    coordinates:
      x: 77.62
      'y': 76.28
    action: navigate
    eventType: navigation
  - nodeId: node-18
    coordinates:
      x: 72.24
      'y': 19.72
    action: navigate
    eventType: navigation
  - nodeId: node-19
    coordinates:
      x: 37.45
      'y': 69.94
    action: navigate
    eventType: navigation
  - nodeId: node-20
    coordinates:
      x: 54
      'y': 96.34
    action: navigate
    eventType: navigation
  - nodeId: node-21
    coordinates:
      x: 25.51
      'y': 75.7
    action: navigate
    eventType: navigation
  - nodeId: node-22
    coordinates:
      x: 10.67
      'y': 28.11
    action: navigate
    eventType: navigation
  - nodeId: node-23
    coordinates:
      x: 66.5
      'y': 47.62
    action: navigate
    eventType: navigation
  - nodeId: node-24
    coordinates:
      x: 93.44
      'y': 14.24
    action: navigate
    eventType: navigation
  - nodeId: node-25
    coordinates:
      x: 84.17
      'y': 52.84
    action: navigate
    eventType: navigation
  - nodeId: node-26
    coordinates:
      x: 61.73
      'y': 42.04
    action: navigate
    eventType: navigation
  - nodeId: node-27
    coordinates:
      x: 15.39
      'y': 20.05
    action: navigate
    eventType: navigation
  - nodeId: node-28
    coordinates:
      x: 2.17
      'y': 19.4
    action: navigate
    eventType: navigation
  - nodeId: node-29
    coordinates:
      x: 29.02
      'y': 15.04
    action: navigate
    eventType: navigation
  - nodeId: node-30
    coordinates:
      x: 15.5
      'y': 60.16
    action: navigate
    eventType: navigation
  - nodeId: node-31
    coordinates:
      x: 27.93
      'y': 9.04
    action: navigate
    eventType: navigation
  - nodeId: node-32
    coordinates:
      x: 13.76
      'y': 58.37
    action: navigate
    eventType: navigation
  - nodeId: node-33
    coordinates:
      x: 70.3
      'y': 0.65
    action: navigate
    eventType: navigation
  - nodeId: node-34
    coordinates:
      x: 42.32
      'y': 5.53
    action: navigate
    eventType: navigation
  - nodeId: node-35
    coordinates:
      x: 80.1
      'y': 99.93
    action: navigate
    eventType: navigation
  - nodeId: node-36
    coordinates:
      x: 5.15
      'y': 77.49
    action: navigate
    eventType: navigation
  - nodeId: node-37
    coordinates:
      x: 36.88
      'y': 17.08
    action: navigate
    eventType: navigation
  - nodeId: node-38
    coordinates:
      x: 49.58
      'y': 94.14
    action: navigate
    eventType: navigation
  - nodeId: node-39
    coordinates:
      x: 40.99
      'y': 90.41
    action: navigate
    eventType: navigation
  - nodeId: node-40
    coordinates:
      x: 35.16
      'y': 98.39
    action: navigate
    eventType: navigation
  - nodeId: node-41
    coordinates:
      x: 75.09
      'y': 88.18
    action: navigate
    eventType: navigation
  - nodeId: node-42
    coordinates:
      x: 33.46
      'y': 28.02
    action: navigate
    eventType: navigation
  - nodeId: node-43
    coordinates:
      x: 55.47
      'y': 15.8
    action: navigate
    eventType: navigation
  - nodeId: node-44
    coordinates:
      x: 66.82
      'y': 48.34
    action: navigate
    eventType: navigation
  - nodeId: node-45
    coordinates:
      x: 0.85
      'y': 74.38
    action: navigate
    eventType: navigation
  - nodeId: node-46
    coordinates:
      x: 89.94
      'y': 81.55
    action: navigate
    eventType: navigation
  - nodeId: node-47
    coordinates:
      x: 2.24
      'y': 55
    action: navigate
    eventType: navigation
  - nodeId: node-48
    coordinates:
      x: 97.5
      'y': 33.68
    action: navigate
    eventType: navigation
edges:
  - source: node-0
    target: ../images/favicon.ico
    action: navigate
  - source: node-1
    target: ../styles/style.css
    action: navigate
  - source: node-2
    target: ../styles/dark.css
    action: navigate
  - source: node-3
    target: ../
    action: navigate
  - source: node-4
    target: '#info'
    action: navigate
  - source: node-5
    target: '#source'
    action: navigate
  - source: node-6
    target: '#templateData'
    action: navigate
  - source: node-7
    target: '#tree'
    action: navigate
  - source: node-8
    target: ../components/ListErrorsComponent.html
    action: navigate
  - source: node-9
    target: '#destroyRef'
    action: navigate
  - source: node-10
    target: '#errors'
    action: navigate
  - source: node-11
    target: '#isSubmitting'
    action: navigate
  - source: node-12
    target: '#settingsForm'
    action: navigate
  - source: node-13
    target: '#user'
    action: navigate
  - source: node-14
    target: '#logout'
    action: navigate
  - source: node-15
    target: '#ngOnInit'
    action: navigate
  - source: node-16
    target: '#submitForm'
    action: navigate
  - source: node-17
    target: ../injectables/UserService.html
    action: navigate
  - source: node-18
    target: Unknown
    action: navigate
  - source: node-19
    target: ../injectables/UserService.html
    action: navigate
  - source: node-20
    target: Unknown
    action: navigate
  - source: node-21
    target: '#logout'
    action: navigate
  - source: node-22
    target: Unknown
    action: navigate
  - source: node-23
    target: 'https://www.typescriptlang.org/docs/handbook/basic-types.html'
    action: navigate
  - source: node-24
    target: Unknown
    action: navigate
  - source: node-25
    target: '#ngOnInit'
    action: navigate
  - source: node-26
    target: Unknown
    action: navigate
  - source: node-27
    target: 'https://www.typescriptlang.org/docs/handbook/basic-types.html'
    action: navigate
  - source: node-28
    target: Unknown
    action: navigate
  - source: node-29
    target: '#submitForm'
    action: navigate
  - source: node-30
    target: Unknown
    action: navigate
  - source: node-31
    target: 'https://www.typescriptlang.org/docs/handbook/basic-types.html'
    action: navigate
  - source: node-32
    target: Unknown
    action: navigate
  - source: node-33
    target: '#destroyRef'
    action: navigate
  - source: node-34
    target: Unknown
    action: navigate
  - source: node-35
    target: Unknown
    action: navigate
  - source: node-36
    target: '#errors'
    action: navigate
  - source: node-37
    target: ../interfaces/Errors.html
    action: navigate
  - source: node-38
    target: Unknown
    action: navigate
  - source: node-39
    target: Unknown
    action: navigate
  - source: node-40
    target: '#isSubmitting'
    action: navigate
  - source: node-41
    target: Unknown
    action: navigate
  - source: node-42
    target: Unknown
    action: navigate
  - source: node-43
    target: '#settingsForm'
    action: navigate
  - source: node-44
    target: Unknown
    action: navigate
  - source: node-45
    target: Unknown
    action: navigate
  - source: node-46
    target: '#user'
    action: navigate
  - source: node-47
    target: ../interfaces/User.html
    action: navigate
  - source: node-48
    target: Unknown
    action: navigate
